# Generated by Django 6.0.5 on 2026-06-01 10:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('inner_diameter', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Внутренний диаметр (мм)')),
                ('outer_diameter', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Наружный диаметр (мм)')),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Высота (мм)')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL изображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name_plural': 'Подшипники',
            },
        ),
        migrations.CreateModel(
            name='BearingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тип подшипника')),
            ],
            options={
                'verbose_name_plural': 'Типы подшипников',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('organization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Организация')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+79\\d{9}$', message='Формат +79xxxxxxxxx')], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Производитель')),
            ],
            options={
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Материал')),
            ],
            options={
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name_plural': 'Статусы заявок',
            },
        ),
        migrations.CreateModel(
            name='PrecisionClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SmallIntegerField(unique=True, verbose_name='Код класса')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Классы точности',
            },
        ),
        migrations.CreateModel(
            name='SealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тип уплотнения')),
            ],
            options={
                'verbose_name_plural': 'Типы уплотнений',
            },
        ),
        migrations.CreateModel(
            name='BearingStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('bearing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='orders.bearing', verbose_name='Подшипник')),
            ],
            options={
                'verbose_name_plural': 'Остатки и цены',
            },
        ),
        migrations.AddField(
            model_name='bearing',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.bearingtype', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='bearing',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='bearing',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.material', verbose_name='Материал'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Номер заявки')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Адрес доставки')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Итоговая сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.customer', verbose_name='Клиент')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='orders.orderstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Email получателя')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('body', models.TextField(verbose_name='Текст письма')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order', verbose_name='Заявка')),
            ],
            options={
                'verbose_name_plural': 'Email уведомления',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена на момент заказа')),
                ('bearing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.bearing', verbose_name='Подшипник')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заявка')),
            ],
            options={
                'verbose_name_plural': 'Позиции заявок',
            },
        ),
        migrations.AddField(
            model_name='bearing',
            name='precision_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.precisionclass', verbose_name='Класс точности'),
        ),
        migrations.AddField(
            model_name='bearing',
            name='seal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.sealtype', verbose_name='Тип уплотнения'),
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('new_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orders.orderstatus', verbose_name='Новый статус')),
                ('old_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orders.orderstatus', verbose_name='Старый статус')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order', verbose_name='Заявка')),
            ],
            options={
                'verbose_name_plural': 'История статусов',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_url', models.URLField(max_length=500, verbose_name='URL файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('bearing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='orders.bearing', verbose_name='Подшипник')),
            ],
            options={
                'verbose_name_plural': 'Техническая документация',
            },
        ),
    ]
