# Generated by Django 6.0.5 on 2026-06-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bearing',
            name='image_url',
        ),
        migrations.AddField(
            model_name='bearing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bearings/', verbose_name='Изображение'),
        ),
    ]
