# Generated by Django 6.0.5 on 2026-06-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_bearing_image_url_bearing_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicaldoc',
            name='file_url',
        ),
        migrations.AddField(
            model_name='technicaldoc',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='Файл документации'),
        ),
    ]
